[server]
port = 8501
headless = true

[theme]
primaryColor = "#00704A"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "Sans Serif"

[client]
showSidebarNavigation = false
